### ISSUE TITLE
is this project can achieve a requirement when right part is  changed,corresponding left part also synchronized change too

### ISSUE THREAD

**Issue by zrwsmd** [CrossBreezeNL/crossmodel#24]
can this project achieve a requirement when right part is  changed,corresponding left part also synchronized change too like this sprotty project(only for old sprotty project,new sprotty project seems  right part is readonly) 
![image](https://github.com/CrossBreezeNL/crossmodel/assets/26995040/63b8c9e6-6f30-4f4a-a1e2-ea07f44af921)

**Comment by harmen-xb** [comment]
Hi @zrwsmd,

Yes, the views are synced. The different perspectives (textual, form and graphical) are synced on every save action.

We choose to do it on every save only, because while changing the textual perspective the state might be unrenderable in the graph and form perspective.

Regards,
Harmen

**Comment by zrwsmd** [comment]
i want to achieve a requirement when graph  changed,corresponding text file(this project is .cm file)  is changed rather than changing the text file  lead to change the graph,can this project achieve this requirement?
