### ISSUE TITLE
New to crossmodel, the theia frontend cannot connect to backend servers

### ISSUE THREAD

**Issue by YourHarbour** [CrossBreezeNL/crossmodel#73]
Hi, 

I'm new to this area and want to have a try on the crossmodel for my old DSL model reimplementation. My old DSL model which requires some graph editing interfaces and text editing interfaces.

I've tried to run the crossmodel with yarn start:electron, but the thiea editor keeps seeking for connection to glsp server(I guess? as its described as the graphical server) and model server, there are no errors showed on the terminal log. Are there any other backend servers that need to start with other commands? 
![image](https://github.com/user-attachments/assets/2a41eefe-c3bf-4880-802c-0fd2f39109f1)

And do you have some examples to help understand the whole project structure, or some other documents on the crossmodel?

Thank you!

**Comment by harmen-xb** [comment]
Hi @YourHarbour,

Good to hear you are trying CrossModel.

I recognize what you are seeing, this is because the workspace is not a CrossModel workspace yet. If you would open the mapping-example example workspace the backend will connect.

This is indeed something we want to imrpove, so this is more clear.

If you have any feedback, please let us know!

Regards,
Harmen.

**Comment by harmen-xb** [comment]
We have added a packaged dockerfile to run the web version of CrossModel. This might be interesting to get a quick look, it will automatically launch with the example workspace.
